IP-адрес и сеть стенда	10.0.0.125/24, шлюз 10.0.0.1, DNS 8.8.8.8,
Открытые порты	22 (SSH), 5432 (PostgreSQL) – только из сети 10.0.0.0/24
Закрытые/ограниченные порты	Все остальные
Политика паролей	Длина >8, разные регистры + цифры + спецсимволы, срок 90 дней
Настройки доступа к СУБД	Pg_hba.conf разрешает подключение только из сети 10.0.0.0/24
