Параметры ВМ/ПК	2 vCPU, 4 ГБ RAM, 30 ГБ HDD, VirtualBox
Имя сервера / хоста	Kolledge-lab-05
Имя базы данных	College_05
Созданные пользователи БД	Сollege_admin, teacher_01, teacher_02, student_viewer, auditor
Служебная учётная запись ОС	Admin
Точка восстановления / снимок	Не требуется
